# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form.registration:
        class: EcocolocsBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }