EcocolocsBundle\Entity\Annonce:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        autheur:
            type: string
            length: 255
        date:
            type: date
        description:
            type: text
    lifecycleCallbacks: {  }
