EcocolocsBundle\Entity\Colocation:
    type: entity
    table: null
    repositoryClass: EcocolocsBundle\Repository\ColocationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        photo:
            type: string
            length: 255
        photoFichier:
        description:
            type: text
        habitant:
            type: text
        action:
            type: text
#        picto
        page:
            type: string
            length: 255
#        date:
#            type: date
    lifecycleCallbacks: {  }
