EcocolocsBundle\Entity\Colocation:
    type: entity
    table: null
    repositoryClass: EcocolocsBundle\Repository\ColocationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            unique: true
        adresse:
            type: string
            length: 255
            nullable: true
        codePostal:
            type: integer
            nullable: true
        ville:
            type: string
            length: 255
            nullable: true
        longitude:
            type: string
            length: 25
        latitude:
            type: string
            length: 25
    lifecycleCallbacks: {  }
