EcocolocsBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            strategy: { generator: "AUTO" }
    fields:
        nom:
            type: string
            length: 255
        motDePasse:
            type: string
            length: 255
        mail:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToOne:
        colocation:
            targetEntity: EcocolocsBundle\Entity\Colocation
            inversedBy: users