ecocolocs_colocation:
    resource: "@EcocolocsBundle/Resources/config/routing/colocation.yml"
    prefix:   /colocation

ecocolocs_homepage:
    path:     /
    defaults: { _controller: EcocolocsBundle:Default:index }

ecocolocs_contact:
    path:     /contact
    defaults: { _controller: EcocolocsBundle:Default:contact }

ecocolocs_manifeste:
    path:     /mouvement
    defaults: { _controller: EcocolocsBundle:Default:manifeste }

ecocolocs_annonce:
    resource: "@EcocolocsBundle/Resources/config/routing/annonce.yml"
    prefix:   /annonces