<?php

namespace EcocolocsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ColocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColocationRepository extends EntityRepository
{
}
